FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.7-buster-build

RUN install_packages \
        jq \
        moreutils \
        libopenjp2-7 \
        libfreetype6-dev \
        libjpeg-dev \
        libtiff5

WORKDIR /usr/app
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY balena-run.sh ./
RUN chmod +x balena-run.sh
CMD ./balena-run.sh

COPY config.sample.json ./
COPY src ./src
